### ISSUE TITLE
Bit vector constructor

### ISSUE THREAD

**Issue by zeeev** [MarcAzar/BitVector#2]
Hi @MarcAzar, 

It appears that this code yields the wrong size of bit vector, or did I call the API wrong?

```import bitvector

var len = 100
var ba = newBitVector[uint](len)
echo ba
````

return: 

BitVector with capacity of 64 bits and 1 unique elements

then :

```import bitvector

proc printBv*(bv: BitVector, n: int) =
 for i in 0..n-1:
  stdout.write(bv[i])
 stdout.write('\n')
var len = 100
var ba = newBitVector[uint](len)
echo ba
printBv(ba, len)
```

result:

```Error: unhandled exception: /Users/zkronenberg/.nimble/pkgs/BitVector-0.4.8/bitvector.nim(63, 9) `i < b.cap and
  0 <= i` Index out of range [AssertionError]
0000000000000000000000000000000000000000000000000000000000000000Error: execution of an external program failed: '/Users/zkronenberg/Desktop/testbv '```

**Comment by MarcAzar** [comment]
Hey Zev,

The echo will print out the capacity of the bitvector along with its
length. The capacity can also be called separately via `cap` and length
can also be called separately via `len`. 

The capacity prints out the number of bits inside the bitvector, in
your case the 100 bits (len = 100), while the `len` will print out the
size of the bitvector which will depend on your choice of base, in your
case size of `uint`. This can get confusing since you are using the
name "len" to represent the capacity of the bitvector. 

Hope this answers your question, let me know if anything else pops
up...

/Marc

**Comment by MarcAzar** [comment]
I have fixed the bug in calculating the capacity of the bitvector. Please note in your case it will report a capacity of 128 and len of 2. Since the size of `uint` is 64 and the request is for 100 bits, the bitvector will now automatically plus one the minimum requested capacity to include all 100 bits.

**Comment by zeeev** [comment]
Hi @MarcAzar,

Thanks for looking into this. I really appreciate this code, and your responsiveness.  Feel free to close this issue. 

One last question while I have your attention. What's the default value of each bit, zero? I'm looking into non-zero bits right after creation of the object. Here's the gist:

``` 

var aCoverage = newBitVector[uint](ovls[0].l1)
echo aCoverage, " ", ovls[0].l1
doAssert aCoverage[0..9] == 0

output

BitVector with capacity of 9088 bits and 142 unique elements 9089
../../../.choosenim/toolchains/nim-#devel/lib/system/fatal.nim(37) sysFatal
Error: unhandled exception: /Users/zkronenberg/tools/nim-pb/src/pbpkg/overlapFilter.nim(142, 11) `aCoverage[0 .. 9] == 0`  [AssertionError]```

**Comment by MarcAzar** [comment]
I'm glad you are finding the library useful! I created it for a personal project but I'm happy to hear others are using it as well.

Yep, currently the bitvector underbelly is using nim's `seq ` and initialization is done with `newSeqOfCap` which reserves memory but does not initialize the sequence, then `setLen` is called to initialize a requested length with zeros. This can be changed to better meet your non-zero initialization by replacing `setLen` with a loop to assign the sequence elements with your initial value.
